### ISSUE TITLE
Unexpected behavior

### ISSUE THREAD

**Issue by ylazy** [jca02266/vscode-align-column#3]
Hi!
Please view the video bellow for more info:

https://github.com/user-attachments/assets/dfbea522-9917-444b-8af0-8ed867170543

I don't want to trim the spaces after `=` characters.

Please consider to fix this.

Thank you!

**Comment by jca02266** [comment]
I added PR #4 

What do you think about this change?

**Comment by ylazy** [comment]
> I added PR #4
> 
> What do you think about this change?

I think it's good but It could be better if we can specify how many spaces to use. In the case above I would like to use 2 spaces.

Thank you!

**Comment by jca02266** [comment]
hmm, I will consider the proposal.

2024年12月24日(火) 12:42 Ylazy ***@***.***>:

**Comment by jca02266** [comment]
Updated PR #4 

I'd like to hear your thoughts.

https://github.com/user-attachments/assets/6c885f39-d292-4126-9bcf-06c2072e2aeb

**Comment by ylazy** [comment]
Thank you for your patient!

I did some research about other similiar alignment extensions, and found [this realign extension](https://marketplace.visualstudio.com/items?itemName=maxhillis.realign) can give us some ideas that can be apply to your extension.

- It should be able to limit the number of matches for each alignment character. Currently your extension are applying alignment for all matches.
- It should be able to control how many spaces to add before/after each alignment character. Currently your extension are adding 1 space before/after each alignment character if there're at least 1 space before/after matches(?)
- It should ignore lines that are single/multiline comments. Currently your extension are affecting to comments.

In my case, if possible, I'd like to add 2 spaces before `:`, 0 space after `:`, 2 spaces before `=`, 2 spaces after `=`.

Then the input seperators field content should be something like this: `|  :|  =  |` (align `:` 1 times, 2 spaces before, 0 space after; align `:` 1 times, 2 spaces befores, 2 spaces after)

Another examples:

without `|` separator:
`:` align `:`, all matches (no limit), 1 minimum space before, 1 minimum space after
`:=` align `:`, all matches (no limit), 1 minimum space before, 1 minimum space after; align `=`, all matches, 1 minimum space before, 1 minimum space after

with `|` separator:
`| : |` align `:`, 1 match limit, 1 minimum space before, 1 minimum space after
`| =3 |` align `=`, 3 matches limit, 1 minimum space before, 1 minimum space after
`|  =*  |` align `=`, all matches (no limit), 2 minimum spaces before, 2 minimum spaces after
`| == |` align `==`, 1 match limit, 1 minimum space before, 1 minimum space after

escaping `|` and ` ` (space) character:
`| \|\| |` align `||`, 1 match limit, 1 minimum space before, 1 minimum space after
`|\ *|` align ` ` (space), all matches (no limit), 0 minimum space before, 0 minimum space after

How do you think about this idea?

Thanks!

**Comment by jca02266** [comment]
I want to keep the functionality simple, so I prefer not to make the rules for writing complex or add too many detailed variations. I think inserting spaces while preserving multi-cursor functionality is a good approach, as it allows users the freedom to add spaces as they like. However, I can't think of any elegant operations to achieve more than this.

**Comment by jca02266** [comment]
I’m planning to prepare for the release of the current PR for now. However, if you come up with a simple and elegant way to achieve what you want, please let me know.

By the way, "realign" is a nice extension.
